[package]
name = "rust-coin-price"
version = "0.1.0"
edition = "2021"
authors = ["Mayank Singh"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.149"
serde_derive = "1.0.149"
serde_json = "1.0.89"
ureq = "2.5.0"